### ISSUE TITLE
interface connect to hoverboard

### ISSUE THREAD

**Issue by Darld-lwi** [Candas1/Hoverboard-Web-Serial-Control#3]
Using: WEB Serial API
Function: Control from USART or IBUS.

Question: what to use to connect hoverboard controller to laptop via USB? Using ST-link v2?

**Comment by darld** [comment]
Hi @Candas1 . I saw your youtube video is using ble to control the hoverboard. Can you show us that how you control the hoverboard via usart with jetsnon nano/rpi/arduino?

**Comment by Candas1** [comment]
Hi, please read the wiki of the hoverboard firmware
https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/wiki/Variant-USART

**Comment by abyy28y** [comment]
hello candas. i wish you are ok. may i ask u if i can use esp32 to control hoverboard main board via web serial control?
and i would be grateful if u provide a connection diagram for how to connect the parts required for web serial control. 
thanks in advance.

**Comment by Candas1** [comment]
Hi,

Web serial control is to be used on a computer or smartphone.
You can use an esp32 as a bluetooth to USART bridge but not as a server to host web serial control.

**Comment by abyy28y** [comment]
> 

thank u so much.

**Comment by Amitkor12** [comment]
> Hi,
> 
> Web serial control is to be used on a computer or smartphone. You can use an esp32 as a bluetooth to USART bridge but not as a server to host web serial control.

Okay, so in this case we should create our own controlling app?
Like say a blinky app for controlling the esp32 and via usart controlling the commands.

**Comment by Candas1** [comment]
Yes
