### ISSUE TITLE
Inquiry about ESP32 BLE Module Integration

### ISSUE THREAD

**Issue by Amitkor12** [Candas1/Hoverboard-Web-Serial-Control#4]
Dear Candas

I hope this message finds you well. Firstly, I want to express my gratitude for creating such a valuable tool. It has greatly enhanced remote controlling with serial tools required for monitoring.

I am currently exploring the possibility of integrating your tool with an ESP32 BLE module to access it on mobile devices. I believe this integration would be extremely useful for our robot controlling.

Could you kindly provide guidance on whether your tool supports ESP32 BLE integration? If so, I would appreciate any information or documentation you could share regarding the process and best practices for achieving this.

We are also making use of the Hoverboard_Firmware_hack_foc for our current project. So this should make it little ease for controlling via web tools.

Thank you once again for your hard work and for providing the community with such a helpful tool. I look forward to your guidance on this matter.

Best regards,
Amit Korgaonkar

**Comment by Candas1** [comment]
https://github.com/Candas1/Hoverboard-Web-Serial-Control/issues/3#issuecomment-1678558671
